# Site settings

title: Insti Insights
email: mythreyi.1.618@gmail.com
description: >-
  Pensively distilled.
baseurl: "/insights"
url: "https://rmythreyi.github.io/insights/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Other settings

show_excerpts: true
hide_credits: false
hide_search: true
